//functional
import Head from "next/head";

//component
import Footer from "./components/footer";
import BannerLine from "./components/bannerLine";
import MainList from "./components/mainList";
import BannerMain from "./components/bannerMain";
import IconFilter from "./components/iconFilter";
import Header from "./components/header";

export default function Home() {
    return (
        <div className="bg-slate-900 overflow-hidden flex">
            <Head>
                <title>Videoowl | 종합 컨텐츠 큐레이션 플랫폼</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/image/logo/logo_small.svg" />
            </Head>

            <div className="flex flex-col w-full">
                <BannerLine></BannerLine>

                <div className="w-full sm:w-[80%] md:w-[75%] lg:w-[70%] xl:w-[65%] 2xl:w-[60%] mx-auto flex-1 p-3">
                    <Header></Header>
                    <BannerMain></BannerMain>
                    <IconFilter></IconFilter>
                    <MainList></MainList>
                    <Footer></Footer>
                </div>
            </div>
        </div>
    );
}
