//functional
import Head from "next/head";

//component
import Footer from "./components/footer";
import BannerLine from "./components/bannerLine";
import MainList from "./components/mainList";
import BannerMain from "./components/bannerMain";
import IconFilter from "./components/iconFilter";
import Header from "./components/header";
import ScrollToTop from "./components/scrollToTop";

export default function Home() {
    return (
        <div className="bg-slate-900 overflow-hidden flex min-h-screen">
            <Head>
                <title>MOABODA | 종합 컨텐츠 큐레이션 플랫폼</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/image/logo/logo2_small.png" />
                <meta name="facebook-domain-verification" content="ny7q7xyyojpqzncsctoa7u7nzjc9q8" />
            </Head>

            <div className="flex flex-col w-full">
                <BannerLine></BannerLine>

                <div className="w-full md:w-[90%] lg:w-[80%] xl:w-[70%] 2xl:w-[60%] mx-auto flex-1 p-3">
                    <Header></Header>
                    <BannerMain></BannerMain>
                    <IconFilter></IconFilter>
                    <MainList></MainList>
                    <Footer></Footer>
                </div>
            </div>
            <ScrollToTop></ScrollToTop>
        </div>
    );
}
